renamed:    common/bl-exit -> files/bl-exit 	renamed:    common/conkyrc -> files/conkyrc 	renamed:    common/keymaps.list -> files/keymaps.list 	renamed:    common/listgen.manual -> files/listgen.manual 	renamed:    common/menu.xml -> files/menu.xml 	renamed:    common/pacman.conf -> files/pacman.conf 	renamed:    common/rc.xml -> files/rc.xml 	renamed:    common/virtualbox.conf -> files/virtualbox.conf 	renamed:    common/wallpaper.jpg -> files/wallpaper.jpg 	renamed:    squiff/.scriptosettings -> scripts/.scriptosettings 	renamed:    squiff/feliz -> scripts/feliz 	renamed:    squiff/running -> scripts/running 	renamed:    squiff/setup -> scripts/setup 	deleted:    squiff/shared

diff --git a/scripts/setup b/scripts/setup
--- a/scripts/setup
+++ b/scripts/setup
@@ -3,24 +3,73 @@
 # The FelizBang installation scripts for Openbox Arch Linux
 # May 2016
 
-# /squiff/setup
-# Semi-graphical Dialog interface
+# setup - User data input stage
 
 # Developed by Elizabeth Mills, incorporating some code adapted from
 # the Evo/Lution script by Carl Duff and AUI scripts by HelmuthDU.
 
-#
+# Listgen functions for displaying options
+# Both functions prepare the array Options[@] for display in a Dialog menu
+declare -a Options  # For caller
+
+listgen1() {
+  Counter=0
+  Options=() # Empty the array
+  # Prepare $1 for dialog menu
+  for item in $1 # Prepare string array of list items passed as $1
+  do
+    Counter=$((Counter+1))
+    Options[${Counter}]="$item"
+    Counter=$((Counter+1))
+    Options[${Counter}]="-"
+  done
+}
+
+listgen2() {
+  Options=() # Empty the array
+  Counter=0
+  for item in $1; do
+    Items[${Counter}]=$item
+    Counter=$((Counter+1))
+  done
+  Counter=0
+  local ItemCounter=0
+  # Import the complex array
+  name=$2[@]
+  LongName=("${!name}")
+  # Combine for dialog menu
+  for item in "${LongName[@]}"; do
+    Options[$((Counter))]="${Items[${ItemCounter}]}"
+    Options[$((Counter+1))]="$item"
+    Counter=$((Counter+2))
+    ItemCounter=$((ItemCounter+1))
+  done
+}
+
 # Functions relevant to users, locations, settings and review
-#
+# ----------------     ------------------------
+# Function    Line     Function            Line
+# ----------------     ------------------------
+# getkeymap     74     FinalCheck           143
+# setlocale     86     ManualSettings       227
+# settimezone  101     ChangeRootPartition  356
+# UserName     120     ChangeSwapPartition  364
+# Hostname     131     ChangePartitions     372
 # ----------------     -----------------------
-# Function    Line     Function           Line
-# ----------------     -----------------------
-# getkeymap     24     FinalCheck           93
-# setlocale     36     ManualSettings      183
-# settimezone   51     ChangeRootPartition 356
-# UserName      70     ChangeSwapPartition 364
-# Hostname      81     ChangePartitions    372
-# ----------------     -----------------------
+
+# Functions relevant to partitioning options
+# -----------------------      ------------------------
+# Functions         Line       Functions           Line
+# -----------------------      ------------------------
+# CheckParts         270       BuildPartitionLists 269
+# Partitioning        75       UpdateArray         293
+# Parted              99       AllocateRoot        382
+# AutoPartition      103       CheckPartition      404
+# AutoWarning        152       AllocateSwap        460
+# FileSystem         167       SetSwapFile         476
+# SetLabel           232       MorePartitions      520
+# EditLabel          247       MakePartition       560
+# -----------------------      ------------------------
 
 getkeymap() {
   ListKbs=`cat keymaps.list`
@@ -217,22 +266,6 @@ ManualSettings() {
     fi
   done
 }
-
-#
-# Functions relevant to partitioning
-#
-# -----------------------      ------------------------
-# Functions         Line       Functions           Line
-# -----------------------      ------------------------
-# CheckParts          24       BuildPartitionLists 269
-# Partitioning        75       UpdateArray         293
-# Parted              99       AllocateRoot        382
-# AutoPartition      103       CheckPartition      404
-# AutoWarning        152       AllocateSwap        460
-# FileSystem         167       SetSwapFile         476
-# SetLabel           232       MorePartitions      520
-# EditLabel          247       MakePartition       560
-# -----------------------      ------------------------
 
 CheckParts() { # First check of available partitions on the system
   # Test for existing partitions
@@ -654,4 +687,313 @@ MakePartition() { # Called by MorePartitions
     fi
   done
   AddPartMount[$ExtraPartitions]="${PartMount}"
+}
+
+# --------------------------
+# Functions             Line
+# --------------------------
+# arch_chroot             75
+# ReflectorMirrorList     79
+# LocalMirrorList         89
+# Partitioning     from  104
+# Review Stage     from  333
+
+# Install Stage    from  377
+# --------------------------
+
+ReflectorMirrorList() { # Use reflector (added to archiso) to generate fast mirror list
+  TPecho "Generating mirrorlist"
+  reflector --verbose -l 5 --sort rate --save /etc/pacman.d/mirrorlist &>> feliz.log
+  if [ $? -gt 0 ]; then
+    LocalMirrorList
+  else
+    chmod +r /etc/pacman.d/mirrorlist &>> feliz.log
+  fi
+}
+
+LocalMirrorList() { # In case Reflector fails, generate and save a shortened
+  # mirrorlist of only the mirrors defined in the CountryCode variable.
+  URL="https://www.archlinux.org/mirrorlist/?country=${CountryCode}&use_mirror_status=on"
+  MirrorTemp=$(mktemp --suffix=-mirrorlist) &>> feliz.log
+  # Use curl to get list of mirrors from the Arch mirrorlist ${URL} to ${MirrorTemp}
+  curl -so ${MirrorTemp} ${URL} &>> feliz.log
+  # Use sed to filter entries
+  sed -i 's/^#Server/Server/g' ${MirrorTemp} &>> feliz.log
+  # Make a safe copy of existing mirrorlist
+  mv -f /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig &>> feliz.log
+  # Replace existing mirrorlist with new local mirrorlist
+  mv -f ${MirrorTemp} /etc/pacman.d/mirrorlist &>> feliz.log
+  chmod +r /etc/pacman.d/mirrorlist &>> feliz.log
+}
+
+Parted() {
+  parted --script /dev/${UseDisk} "$1" &>> feliz.log
+}
+
+MakePartitionList() {
+  # Call BuildPartitionLists function to generate an array of partitions
+  # This is not a first call, so first empty the existing array
+  local x=0
+  local HowMany="${#PartitionArray[@]}"
+  until [ ${x} -eq ${HowMany} ]
+  do
+    unset PartitionArray[$x]
+    x=$((x+1))
+  done
+  BuildPartitionLists # Then rebuild
+}
+
+BuildPartitionLists() { # First called by CheckParts to generate details of partitions
+  # for display, then by feliz to prepare partition arrays for selection for root, swap and others
+  # 1) First get a list of all partitions up to sda99 | select first field | remove /dev/ | remove colon
+  ListTypeIDs=`sudo blkid /dev/sd* | grep ' TYPE' | awk '{print $1}' | cut -c 6- | sed s/://g`
+  # Then get matching list of types, removing unwanted text (TYPE=) and quotes
+  ListTypes=`sudo blkid /dev/sd* | grep ' TYPE' | awk '{print $(NF-1)}' | cut -c 6- | sed s/\"//g`
+  # Add records from those two indexed arrays into the associative array
+  local Counter=0
+  for i in ${ListTypeIDs}
+  do
+    x=0
+    for l in ${ListTypes}
+    do
+      if [ $x -eq $Counter ]; then
+        FileSystem[$i]=$l # ... get the matching type
+      break
+      fi
+      x=$((x+1))
+    done
+    Counter=$((Counter+1))
+  done
+  # 2) Find all up to sd*99 with LABEL | select 1st field | remove /dev/ | remove colon
+  ListLabelledIDs=`sudo blkid /dev/sd* | grep LABEL | awk '{print $1}' | cut -c 6- | sed s/://g`
+  # If at least one labelled partition found, get a matching list of labels (remove quotes)
+  if [ -n "$ListLabelledIDs" ]; then
+    ListLabelledLabels=`sudo blkid /dev/sd* | grep LABEL | awk '{print $2}' | cut -c 7- | sed s/\"//g`
+  fi
+  # Add records from those two indexed arrays into associative array
+  Counter=0
+  for i in ${ListLabelledIDs}
+  do
+    x=0
+    for l in ${ListLabelledLabels}
+    do
+      if [ $x -eq $Counter ]; then
+        Labelled[$i]=$l # ... get the matching label
+      break
+      fi
+      x=$((x+1))
+    done
+    Counter=$((Counter+1))
+  done
+  local HowManyLabelled="${#Labelled[@]}"
+  # 3) Find any partitions flagged as bootable
+  ListAll=`sudo sfdisk -l | grep /dev | grep '*' | awk '{print $1}' | cut -c 6-`
+  declare -a Flagged
+  Counter=0
+  for i in $ListAll
+  do
+    Flagged[${Counter}]="$i"
+    Counter=$((Counter+1))
+  done
+  local HowManyFlagged="${#Flagged[@]}"
+  # 4) Prepare list of short identifiers (sda1 sda2 ...)
+  PartitionList=""
+  ShowPartitions=`lsblk -l | grep 'part' | awk '{print $1}'`
+  # 5) Run through short identifiers, checking the three arrays for a match
+  Counter=0 # For count of partitions
+  Label=""
+  for part in ${ShowPartitions}
+  do
+  # First test Flagged
+    local x=0
+    until [ ${x} -eq ${HowManyFlagged} ]
+    do
+      if [ $part = "${Flagged[$x]}" ]; then
+        Bootable="(Bootable)"
+        break
+      else
+        Bootable=""
+      fi
+      x=$((x+1))
+    done
+    # Next test Labelled
+    ThisPart=${Labelled[${part}]} # Find the record in Labelled that matches the current iteration
+    if [ -n "${ThisPart}" ]; then
+      Label="${ThisPart}"
+    fi
+    # Finally get the filesystem type
+    ThisPart=${FileSystem[${part}]} # Find the record in FileSystem that matches the current iteration
+    LongID=`lsblk -l | grep ${part} | awk '{print $1 " " $4 " " $7}'`
+    PartitionArray[${Counter}]="$LongID $ThisPart ${Label} ${Bootable}"
+    Label=""
+    # Save the short ID for later functions
+    PartitionList="${PartitionList} ${part}"
+    (( Counter+=1 ))
+  done
+  PARTITIONS=${Counter}
+}
+
+UpdateArray() { # Remove the selected partition from $PartitionArray[]
+  # Called by AllocateRoot, AllocateSwap and MorePartitions
+  local Counter=0
+  declare -a NewArray  # Empty NewArray
+  # Build NewArray excluding the partition selected in the calling function
+  for p in "${PartitionArray[@]}"
+  do
+    First=`echo $p | cut -c 1-5`
+    if [ $First ]; then
+      if [ ${PassPart} != ${First} ]; then
+        NewArray[${Counter}]="$p"
+        (( Counter+=1 ))
+      fi
+    fi
+  done
+  # Then copy NewArray into PartitionArray
+  Counter=0
+  for p in "${NewArray[@]}"
+  do
+    PartitionArray[${Counter}]=${NewArray[$Counter]}
+    Counter=$((Counter+1))
+  done
+  unset PartitionArray[$Counter] # Delete the last element
+}
+
+RunAutoPart() {
+  GrubDevice="/dev/${UseDisk}"
+  Home="N"
+  # Get disk size
+  DiskSize=`lsblk -l | grep "${UseDisk}\ " | awk '{print $4}' | sed s/G//g`
+  # Create partitions and set variables for mounting
+  Parted "mklabel msdos"
+  if [ $DiskSize -ge 40 ]; then
+    # Device is large enough for a separate /home partition and larger
+    # /root (20 GiB) and /swap (8 GiB)
+    Parted "mkpart primary linux-swap 1MiB 8GiB"
+    SwapPartition="${GrubDevice}1"
+    MakeSwap="Y"
+    # Root partition 15GiB
+    Parted "mkpart primary ext4 8GiB 28GiB"
+    Parted "set 2 boot on"
+    RootPartition="${GrubDevice}2"
+    RootType="ext4"
+    # Home partition = remainder (size from 19GiB to maximum available)
+    Parted "mkpart primary ext4 28GiB 100%"
+    AddPartList[0]="${GrubDevice}3" # Add to the array of additional partitions
+    AddPartMount[0]="/home"
+    AddPartType[0]="ext4"
+    Home="Y"
+  elif [ $DiskSize -ge 30 ]; then
+    # Device is just large enough for a separate /home partition
+    # Swap 4GiB
+    Parted "mkpart primary linux-swap 1MiB 4GiB"
+    SwapPartition="${GrubDevice}1"
+    MakeSwap="Y"
+    # Root partition 15GiB
+    Parted "mkpart primary ext4 4GiB 19GiB"
+    Parted "set 2 boot on"
+    RootPartition="${GrubDevice}2"
+    RootType="ext4"
+    # Home partition = remainder (size from 19GiB to maximum available)
+    Parted "mkpart primary ext4 19GiB 100%"
+    AddPartList[0]="${GrubDevice}3" # Add to the array of additional partitions
+    AddPartMount[0]="/home"
+    AddPartType[0]="ext4"
+    Home="Y"
+  elif [ $DiskSize -ge 18 ]; then
+    # Swap 4Gib and one main partition up to 20GiB
+    Parted "mkpart primary linux-swap 1MiB 4GiB"
+    SwapPartition="${GrubDevice}1"
+    MakeSwap="Y"
+    Parted "mkpart primary ext4 4GiB 100%"
+    Parted "set 2 boot on"
+    RootPartition="${GrubDevice}2"
+    RootType="ext4"
+  elif [ $DiskSize -gt 10 ]; then
+    # Swap 2Gib and one main partition up to 16GiB
+    Parted "mkpart primary linux-swap 1MiB 2GiB"
+    SwapPartition="${GrubDevice}1"
+    Parted "mkpart primary ext4 2GiB 100%"
+    Parted "set 2 boot on"
+    RootPartition="${GrubDevice}2"
+    RootType="ext4"
+    SwapFile="2G"
+    SwapPartition=""
+  else # If disk < 10 Gb
+    # Swap file and one main partition up to 10GiB
+    Parted "mkpart primary ext4 1MiB 100%"
+    Parted "set 1 boot on"
+    RootPartition="${GrubDevice}1"
+    RootType="ext4"
+    SwapFile="2G"
+    SwapPartition=""
+  fi
+  ShowPart1="Swap: `lsblk -l | grep "${UseDisk}1" | awk '{print $4}'`" >/dev/null
+  ShowPart2="Root: `lsblk -l | grep "${UseDisk}2" | awk '{print $4}'`" >/dev/null
+  ShowPart3=""
+  AutoPart=1 # Set flag to 'on' for mounting
+}
+
+SetLabel() { # Called from the root, swap and extra partitions routines
+# ... each passing a single argument containing the partition ID
+# Build an associative array of partitions (LabellingArray[]) as
+# declared in felizrunning with other arrays
+PartitionID=$1
+local HowMany="${#PartitionArray[@]}"
+local x=0
+until [ ${x} -eq ${HowMany} ]
+do
+  CompareID=`echo ${PartitionArray[${x}]} | awk '{print $1}'`
+  if [ -z ${CompareID} ]; then
+    x=$((x+1))
+    continue
+  fi
+  if [ ${CompareID} = ${PartitionID} ]; then # If the partition is in the array, it has a label
+  #  Label=`echo ${PartitionArray[${x}]} | awk '{print $4}'` # Save the label
+  Label=`echo ${PartitionArray[${x}]}`
+  fi
+  x=$((x+1))
+done
+}
+
+#
+# Review stage ---------------------------------------------------------
+#
+
+ChangeRootPartition() {
+# Start array with SwapPartition
+  Ignorelist[0]=${SwapPartition}
+  local Counter=1
+  AddExtras
+  MakePartitionList
+}
+
+ChangeSwapPartition() {
+# Start array with RootPartition
+  Ignorelist[0]=${RootPartition}
+  Counter=1
+  AddExtras
+  MakePartitionList
+}
+
+ChangePartitions() {
+  # Copy RootPartition and SwapPartition into temporary array
+  Ignorelist[0]=${RootPartition}
+  local Counter=1
+  if [ ${SwapPartition} ]; then
+    Ignorelist[1]=${SwapPartition}
+    Counter=2
+  fi
+  Ignores=${#Ignorelist[@]} # Save a count for later
+  MakePartitionList
+}
+
+AddExtras() {
+  # Called by ChangeSwapPartition and ChangeRootPartition with
+  # Ignorelist started and Counter set to next record number
+  # Add each field (extra partition) from AddPartList into the array:
+  for a in ${AddPartList[@]}; do
+    Ignorelist[$Counter]=$a
+    Counter=$((Counter+1))
+  done
+  Ignores=${#Ignorelist[@]} # Save a count for later
 }
